<?php
declare(strict_types=1);

const TLS_VERSION_1_0 = 0x0301;
const TLS_VERSION_1_1 = 0x0302;
const TLS_VERSION_1_2 = 0x0303;
const TLS_VERSION_1_3 = 0x0304;

const TLS_HANDSHAKE_CLIENT_HELLO = 1;
const TLS_HANDSHAKE_SERVER_HELLO = 2;
const TLS_HANDSHAKE_CERTIFICATE = 11;
const TLS_HANDSHAKE_SERVER_HELLO_DONE = 14;
const TLS_HANDSHAKE_CLIENT_KEY_EXCHANGE = 16;
const TLS_HANDSHAKE_FINISHED = 20;

const TLS_CONTENT_HANDSHAKE = 22;
const TLS_CONTENT_APPLICATION_DATA = 23;
const TLS_CONTENT_ALERT = 21;
const TLS_CONTENT_CHANGE_CIPHER_SPEC = 20;
const TLS_CONTENT_HEARTBEAT = 24;